### ISSUE TITLE
User testing

### ISSUE THREAD

**Issue by Johanna-hub** [fac-12/Little-Window#103]
- [x] online and in-person user testing at the beginning of Week 2
- [x] test different sizes of box
- [x] make a feedback form
