### ISSUE TITLE
Existing UX improvements

### ISSUE THREAD

**Issue by jamiecoe** [fac-12/Little-Window#105]
- [x] Input Submit button colour #92 
- [x] Options buttons more readable colour #91 
- [x] Disable typing while little window is typing #72, should fix remaining dots issue #75  
- [x] Add `pointer` cursor for any buttons (incl refresh button) #73

**Comment by Johanna-hub** [comment]
closed by #114 & #112
