### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by rb50** [fac-12/Little-Window#106]
- [x] Refreshing during waiting #81 
- [x] Dots sometimes remain on the screen #75 
- [x] Save message conversationId #70 
- [x] Submit button flashing when input field is disabled #59 
- [x] Save conversation error #143
