### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by rb50** [fac-12/Little-Window#107]
- [ ] DialogFlow Error Handling #31 
- [x] Google Sheets Error Handling #109  
- [ ] Database error Handling #110
