### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by jamiecoe** [fac-12/Little-Window#108]
- [x] Destructuring Component on import #95 
- [x] Calling saveConversation() with every new message #93 
- [x] Code repetition in button #90 
- [x] Move nodemon to devDependencies #89 
- [x] Styling in Input.js #87 
- [x] Passing style down in Div component #86 
- [x] Database for development #84 
- [ ] Mixture of CSS units #82 
- [x] Function within the render of message #80 
- [x] Buttons naming and styling #79 
- [x] Asset storage #77 
- [x] create-react-app README #71 
- [x] using saveChatLog? #68 
- [x] Empty files #67 
- [x] Add `PropTypes` checks in React components
- [x] Refactor `userMessage.js` - maybe move some functions to their own files
- [x]  Unnecessary isWaiting property #135 
- [x]  Refactoring nested maps #138

**Comment by rb50** [comment]
Issue #82 remains open to be worked on when sizing has been agreed
