### ISSUE TITLE
Integrate with Google Sheets

### ISSUE THREAD

**Issue by jamiecoe** [fac-12/Little-Window#12]
- [x] Add resources to GS
- [x] Connect to Node Server and DF
- [x] Guide for Chayn volunteers
- [ ] Error handling

**Comment by rb50** [comment]
Google Sheets Error handling replaced by #109
