### ISSUE TITLE
Save chat-logs to DB

### ISSUE THREAD

**Issue by jamiecoe** [fac-12/Little-Window#13]
- [x] Research best way of doing this
- [x] Check we're inline with GDPR 
- [x] Add consent message in FE
