### ISSUE TITLE
FE interface

### ISSUE THREAD

**Issue by jamiecoe** [fac-12/Little-Window#14]
Use Styled Components

- [x] Consent Message
- [x] Chayn design
- [x] Option buttons (postbacks)
- [x] Input box
- [x] Message box
- [x] Minimise button
- [x] Test on Wordpress integration
- [x] Resources links (post backs and link to URL)
- [x] Refresh button
- [x] Securikitty image
- [x] Waiting dots (static dots to begin with)
- [x] Button styling #159 
- [x] User select cat #161 
- [x] Change colour of links #162 
- [x] Have description with resource links #165 
- [x] Change minimise button to double arrows

**Comment by mcelearr** [comment]
1. Do you need GDPR consent? If someone types 'my name is jimmy I live on blah street' I don't think it counts as personal information http://www.dataprotectionpeople.com/what-is-personal-data/ because it isn't 'recorded with the intention that it should be processed' or 'recorded as part of a relevant filing system'. Please look into this a bit more because I'm not allowed to advise you.

2. Don't try and build the chat components from scratch yourselves. Here are some open source react chat UIs to look into. I'm sure there are many more:
https://github.com/brandonmowat/react-chat-ui
https://www.npmjs.com/package/react-chat-window
https://github.com/Detaysoft/react-chat-elements

**Comment by njseeto** [comment]
🎉 ✨🎉 ✨All done! 🎉 ✨🎉 ✨
