### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by jamiecoe** [fac-12/Little-Window#15]
- [x] Express setup
- [x] Routes setup
- [x] Connect to DF
- [x] Connect to Google Sheets
- [x] Serve up FE
- [x] Connect to AWS database

**Comment by njseeto** [comment]
Need to add 'DivorceGlobal' to userMessage.js line 20.
