### ISSUE TITLE
Slow down response from Little Window

### ISSUE THREAD

**Issue by Johanna-hub** [fac-12/Little-Window#97]
User feedback is that when country resources are presented, it is very overwhelming.  Also the first messages are too quick.

- [x] Resources need to be slowed down a lot when presented
- [x]  Responses should be slowed down when there's 2 or 3 in a row and the user has a lot to read
- [ ] Test with users in FAC

**Comment by rb50** [comment]
Testing to be done within overall user testing
